#!/usr/bin/env sh

echo "Running pre-push checks..." >&2

echo "Linting..." >&2

yarn run lint >&2
if [ $? -ne 0 ]; then
    echo "[ACM DEV NOTE] Lint failed. Fix Linting Issues by running 'yarn run lint:fix'" >&2
    echo "[ACM DEV NOTE] Push aborted!" >&2
    exit 1
fi

echo "Prettier..." >&2

yarn run prettier
if [ $? -ne 0 ]; then
    echo "[ACM DEV NOTE] Prettier failed. Fix Linting Issues by running 'yarn run prettier:fix'" >&2
    echo "[ACM DEV NOTE] Push aborted!" >&2
    exit 1
fi

echo "Pre-push checks passed. Proceeding with push." >&2
exit 0